-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 20:35:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teste_turing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste_turing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste_turing` DEFAULT CHARACTER SET utf8 ;
USE `teste_turing` ;

-- -----------------------------------------------------
-- Table `teste_turing`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`pergunta` (
  `idpergunta` INT NOT NULL AUTO_INCREMENT,
  `enunciado` TEXT NOT NULL,
  PRIMARY KEY (`idpergunta`),
  UNIQUE INDEX `idpergunta_UNIQUE` (`idpergunta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_turing`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`resposta` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `idpergunta` INT NOT NULL,
  `resposta` TEXT NOT NULL,
  `tipo_resposta` TINYINT NOT NULL,
  PRIMARY KEY (`idresposta`, `idpergunta`),
  UNIQUE INDEX `idresposta_UNIQUE` (`idresposta` ASC) VISIBLE,
  INDEX `fk_resposta_pergunta_idx` (`idpergunta` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_pergunta`
    FOREIGN KEY (`idpergunta`)
    REFERENCES `teste_turing`.`pergunta` (`idpergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_turing`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`partida` (
  `idpartida` INT NOT NULL AUTO_INCREMENT,
  `data_hora_inicio` TIMESTAMP NOT NULL,
  `data_hora_fim` TIMESTAMP NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpartida`),
  UNIQUE INDEX `idquem_respondeu_UNIQUE` (`idpartida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_turing`.`jogada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`jogada` (
  `idjogada` INT NOT NULL AUTO_INCREMENT,
  `numero_jodada` INT NOT NULL,
  `idpergunta` INT NOT NULL,
  `idresposta` INT NOT NULL,
  `partida_idpartida` INT NOT NULL,
  PRIMARY KEY (`idjogada`, `idpergunta`, `idresposta`, `partida_idpartida`),
  INDEX `fk_jogada_pergunta1_idx` (`idpergunta` ASC) VISIBLE,
  INDEX `fk_jogada_resposta1_idx` (`idresposta` ASC) VISIBLE,
  INDEX `fk_jogada_partida1_idx` (`partida_idpartida` ASC) VISIBLE,
  CONSTRAINT `fk_jogada_pergunta1`
    FOREIGN KEY (`idpergunta`)
    REFERENCES `teste_turing`.`pergunta` (`idpergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogada_resposta1`
    FOREIGN KEY (`idresposta`)
    REFERENCES `teste_turing`.`resposta` (`idresposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogada_partida1`
    FOREIGN KEY (`partida_idpartida`)
    REFERENCES `teste_turing`.`partida` (`idpartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
