-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 21:01:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teste_turing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste_turing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste_turing` DEFAULT CHARACTER SET utf8 ;
USE `teste_turing` ;

-- -----------------------------------------------------
-- Table `teste_turing`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`pergunta` (
  `idpergunta` INT NOT NULL AUTO_INCREMENT,
  `enunciado` TEXT NOT NULL,
  PRIMARY KEY (`idpergunta`),
  UNIQUE INDEX `idpergunta_UNIQUE` (`idpergunta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_turing`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`resposta` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `resposta` TEXT NOT NULL,
  `pergunta_idpergunta` INT NOT NULL,
  PRIMARY KEY (`idresposta`, `pergunta_idpergunta`),
  UNIQUE INDEX `idresposta_UNIQUE` (`idresposta` ASC) VISIBLE,
  INDEX `fk_resposta_pergunta_idx` (`pergunta_idpergunta` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_pergunta`
    FOREIGN KEY (`pergunta_idpergunta`)
    REFERENCES `teste_turing`.`pergunta` (`idpergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_turing`.`resposta_ia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_turing`.`resposta_ia` (
  `idresposta_ia` INT NOT NULL AUTO_INCREMENT,
  `resposta_ia` VARCHAR(45) NOT NULL,
  `pergunta_idpergunta` INT NOT NULL,
  PRIMARY KEY (`idresposta_ia`, `pergunta_idpergunta`),
  UNIQUE INDEX `idresposta_ia_UNIQUE` (`idresposta_ia` ASC) VISIBLE,
  INDEX `fk_resposta_ia_pergunta1_idx` (`pergunta_idpergunta` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_ia_pergunta1`
    FOREIGN KEY (`pergunta_idpergunta`)
    REFERENCES `teste_turing`.`pergunta` (`idpergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
